# Generated by Django 5.2.5 on 2025-08-29 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField(max_length=50)),
                ('emp_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('salary', models.IntegerField(default=20000)),
                ('department', models.CharField(max_length=50)),
            ],
        ),
    ]
